sudo: required

language: java
jdk:
 - openjdk8
 
services:
  - docker
 
before_install:
  - chmod +x mvnw
  
script: ./mvnw clean install 

after_success:
  - docker build -t pointinsights/springboot-git-alpha .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push pointinsights/springboot-git-alpha
  


deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: springboot-git-alpha
  env: SpringbootGitAlpha-env
  bucket_name: elasticbeanstalk-us-east-2-693831461729
  bucket_path: springboot-git-alpha
  on: 
    branch: main
  access_key_id: $AWS_ID
  secret_access_key: $AWS_PASSWORD
  

 
