language: java
jdk:
 - openjdk8
 
services:
  - docker
 
before_install:
  - chmod +x mvnw
  - docker build -t $DOCKER_ID/springboot-git-alpha
  - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_ID" --password-stdin  
  - docker push pointinsights/springboot-git-alpha
  
script: ./mvnw clean install 

  
 
