language: java
jdk:
 - openjdk8
 
before_install:
  - chmod +x mvnw
  
script: ./mvnw clean install 

after_success:
  - docker build -t pointinsights/springboot-git-alpha
  - docker run pointinsights/springboot-git-alpha
  - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_ID" --password-stdin
  - docker push pointinsights/springboot-git-alpha
 
 
